# Generated by Django 4.1.7 on 2023-04-04 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0003_fuel_remove_ordermodels_items_delete_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fuel',
            name='category',
        ),
        migrations.AddField(
            model_name='fuel',
            name='name',
            field=models.CharField(default='Petrol/diesel', max_length=100),
        ),
        migrations.AddField(
            model_name='fuel',
            name='Category',
            field=models.ManyToManyField(related_name='Name', to='Customer.category'),
        ),
    ]
