# Generated by Django 4.1.7 on 2023-04-06 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0004_remove_fuel_category_fuel_name_fuel_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='order_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=20)),
                ('Phone', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=3)),
            ],
        ),
    ]
