# Generated by Django 4.1.7 on 2023-04-06 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0005_order_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_data',
            old_name='Phone',
            new_name='phone',
        ),
    ]
