# Generated by Django 4.1.7 on 2023-04-06 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0006_rename_phone_order_data_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_data',
            name='category',
            field=models.ManyToManyField(to='Customer.category'),
        ),
    ]
