# Generated by Django 4.1.7 on 2023-04-06 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0008_remove_order_data_category_order_data_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeralaHub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hub_name', models.CharField(max_length=20)),
                ('hub_dist', models.CharField(max_length=20)),
                ('hub_num', models.CharField(max_length=10)),
            ],
        ),
    ]
